### ISSUE TITLE
How to compile small vim.js?

### ISSUE THREAD

**Issue by emnh** [coolwanglu/vim.js#22]
How did you get a small file of only 5.8 MB?
I compile using emscripten 1.2.9 SDK and build.sh using the features you set but I get a 122 MB file.

I tried running the closure compiler to minify it, but it runs out of memory even with java -Xmx2048m.

With emcc -O2 I get a 33 MB file, but then it doesn't work.

**Comment by coolwanglu** [comment]
If you mean the old version, that was compiled without ASYNCIFY, and with streamline.js and some hacks. The result is small but not fast in Firefox.

The current version is compiled with ASYNCIFY, in order to enable ASM.js, which is much larger.

I just compiled again and I got a 22M `vim.js`. Maybe the old version is still useful for NW.js

**Comment by coolwanglu** [comment]
Also make sure that `-Oz` is enabled for `emcc`.

**Comment by emnh** [comment]
22M is still 100M less than mine. Yes, -Oz is enabled. I wonder what else could be different.

**Comment by coolwanglu** [comment]
Um, I forgot to remove `-O0` in the git repo, which was for debugging. Try to remove it before try again.

**Comment by emnh** [comment]
Ok, I tried -O2 again. Same as before, I got a 33 MB file with that, but it was hanging on the loading screen. With this, I got an error in the JS console: "Uncaught SyntaxError: Unexpected token else" vim.js line 23 when trying to load the "web" folder in Chrome.

I am considering running vim inside jor1k with a full linux instead though, since it may be fast enough, and I see vim.bz2 for RISC is actually only 334K so you can save a lot on file size by running emulation in browser compared to emscripten, plus having a more powerful environment with a whole OS.

**Comment by emnh** [comment]
Also tried with -O1, but that was also 122 MB, same as -O0.

**Comment by coolwanglu** [comment]
Ok, so that almost works.

But me too, I found a new bug in emscripten (kripken/emscripten#3154), so currently we just have to wait. 

You may also try the emterpreter feature, although I have not tried myself, and it might be very slow.

**Comment by emnh** [comment]
Ok. Thanks!

I have a [working demo](http://alexis.lart.no:3000/?html,js,vim,output) of Native Vim integration with JSBin running under [jor1k](http://github.com/s-macke/jor1k/) linux RISC emulation now. Try it you like, see if it is too slow. Maybe I'll try vim.js as well.

**Comment by coolwanglu** [comment]
Now the bug of emscripten has been fixed, and I've updated a new version in `NW.js/`

Please try again.

**Comment by emnh** [comment]
The NW.js version that you compiled worked for me in node webkit :).
I am still waiting for the compilation of emscripten incoming to compile it myself.

The NW.js version doesn't run in Chrome or Firefox though and fails with "Assertion failed: undefined" vim.js line 1. Did you change anything to specifically target NW.js?

**Comment by emnh** [comment]
Yes, everything works now. I compiled with emscripten incoming and got same size as yours, 25 MB.

**Comment by coolwanglu** [comment]
You can try to copy vim.js* to web/ and open the vim.html with browsers.
As far as I can remember, in the NW.js version, NODFS is used to mount the
filesystem, which may lead to error in non-Node environments.
