### ISSUE TITLE
Try new version with EMTERPRETIFY to reduce size and startup time

### ISSUE THREAD

**Issue by emnh** [coolwanglu/vim.js#29]
See https://blog.mozilla.org/research/2015/02/23/the-emterpreter-run-code-before-it-can-be-parsed/ and https://github.com/kripken/emscripten/wiki/Emterpreter .

**Comment by coolwanglu** [comment]
Right, I'll probably give a try, but not sure if it will be too slow for actual usage.

**Comment by coolwanglu** [comment]
Done :)
http://coolwanglu.github.io/vim.js/emterpreter/vim.html

The size is much smaller now, and seems that I cannot feel any slowdown.

**Comment by emnh** [comment]
Excellent :)

**Comment by coolwanglu** [comment]
@emnh Now I guess I would not worry about size, can you change your PR to the `emterpreter` branch?
Thanks.

**Comment by emnh** [comment]
There is no `emterpreter` branch. Did you forget to push it? Or do you mean gh-pages?

**Comment by coolwanglu** [comment]
Oops. I will push it later. Sorry!
2015-3-4 下午5:51于 "Eivind Magnus Hvidevold" <notifications@github.com>写道：

**Comment by coolwanglu** [comment]
Done :)

**Comment by emnh** [comment]
Cool :) . I added a new PR for the emterpreter branch. PS: You may want to merge the non-multibyte fixes for the main branch as well.

**Comment by emnh** [comment]
I updated my [Firefox plugin](https://addons.mozilla.org/en-US/firefox/addon/vimjs-extension/) to use the emterpreter multibyte version if you want to try it.

**Comment by coolwanglu** [comment]
@emnh Great, I'll add a link in README. By the way, seems that the latest emscripten enabled dynamic growing HEAP by default, which is also supported by the latest Firefox. I guess you can tweak the initial memory size if necessary.
